stage('SonarQube Analysis') {
    steps {
        dir('backend') {
            withCredentials([string(credentialsId: 'jenkins-sonar', variable: 'SONAR_TOKEN')]) {
                sh """
                    mvn sonar:sonar \
                    -Dsonar.login=${SONAR_TOKEN} \
                    -Dsonar.host.url=https://sonarcloud.io \
                    -Dsonar.organization=ameny323 \
                    -Dsonar.projectKey=ameny323_DevOpsProject
                """
            }
        }
    }
}